### ISSUE TITLE
Upload Flowtracker2 .ft files direct to AQ NG

### ISSUE THREAD

**Issue by yanxuYX** [AquaticInformatics/flowtracker2-field-data-plugin#42]
I was able to import a FT2 measurement file (Bonnechere_20200305.ft) into AQ NG Dev (02KC009) and see the discharge details (see screen shot below). However, I don’t think the plug in is working as it should:

there seems to be some errors with the imported data and how they are displayed in NG. I have not looked at all the details, but note a few things already

the velocity measurement points are not plotted correctly (see the 0.8d velocities are in ice?!)

In the table, and when I hover over any segment, the vertical number is always 0 (see below)

The start and end edges (water surface = 0) are labelled as Open Water in the table (under “Measurement 
![image-20200310-141059](https://user-images.githubusercontent.com/56357108/76649367-e43c0700-6536-11ea-8ab3-d3c3ecb49d8d.png)

 

Thanks just what I saw in the first few minutes of looking at this. I think this should be investigated further to confirm the plug in captures all the FT2 details properly before pushing to Production.

Also, 

2. The “Technology” section remains empty. 
![image-20200310-140422](https://user-images.githubusercontent.com/56357108/76649318-c9699280-6536-11ea-941e-087ddaea7ac0.png)

Here is a sample plot from FlowTracker2 software (to show how the plot, with velocity points and ice should look).

**Comment by DougSchmidt-AI** [comment]
Thanks Xu, I'll take a look. Can you rename the file from *.ft to *.zip and attach it here?

**Comment by DougSchmidt-AI** [comment]
OK, I was able to pull the file from the server. I'll take a look.

**Comment by DougSchmidt-AI** [comment]
OK, there are 2 problems here. One can be fixed in the plugin, but the other is a Springboard UI bug and will need to wait for a product fix.

None of these bugs result in the wrong stage/discharge values being reported elsewhere in AQTS, so they probably are not a showstopper.

## No Station # import

This is the plugin bug, which can be easily fixed. All the verticals shown in Springboard said they were all "Vertical 0". It turns out that the FlowTracker2 data doesn't actually have a property that stores the "Station #" you see in the FlowTracker2 software.

But it is easy enough to infer a sequence from 0 to n-1, to match the FlowTracker2 software.
![image](https://user-images.githubusercontent.com/54773/76669222-fd00e880-6547-11ea-9ee6-bbd2acceaed7.png)

![image](https://user-images.githubusercontent.com/54773/76669252-1b66e400-6548-11ea-9e16-3eb9f42bfbc3.png)

## Point depths with ice don't draw properly

Taking a look at vertical/station # 21 (highlighted above), it is clear that the point measurement is being drawn at 0.28 m below the water surface (obscured by the ice), instead of at 0.28m + 0.44m = 0.72m.

So the bug here is in the Springboard UI. It is not apparently offseting the velocity observation depth (0.28m) by the ice thickness (0.44m). I've reported that display-only bug and it will need to be fixed in the core AQTS product.

**Comment by DougSchmidt-AI** [comment]
Fixed by #43 in [v19.2.9](https://github.com/AquaticInformatics/flowtracker2-field-data-plugin/releases/tag/v19.2.9)
